version: '3'

vars:
  HOSTS:
    # There has to be /etc/nixos/hosts/<host>/configuration.nix for each HOST
    - host1
    - host2
    - host3
    - host4.domain

  HOST_ALIASES:
    map:
      host2: host2.domain2.example
      host2: host3.domain3.example
